/*
Walking Robot TurtleV1
Licensed GNU GPLv3 by VN ROBOT INC 2023
Arduino nano
Manager file
*/

/*
input data
  current
    m_robotState.currentStateNow
      C_LOW_BATTERY,
      C_DEAD_BATTERY,
      C_HIGH_CURRENT,
      C_LOW_CURRENT,
      C_NORMAL  
  gyro
    m_gyroState.stateGyro          
      GYRO_NORM,
      GYRO_UPSIDEDOWN,
      GYRO_FELL_LEFT,
      GYRO_FELL_RIGHT,
      GYRO_FELL_FRONT,
      GYRO_FELL_BACK,
      GYRO_FOLLING_LEFT,
      GYRO_FOLLING_RIGHT,
      GYRO_FOLLING_FRONT,
      GYRO_FOLLING_BACK,
      GYRO_SHAKEN,
      GYRO_TURNED_RIGHT,
      GYRO_TURNED_LEFT
  inputs
    m_robotState.inputStateNow
      IN_WALL_FRONTLEFT,
      IN_WALL_FRONTRIGHT,
      IN_WALL_LEFT,
      IN_WALL_RIGHT,
      IN_OBSTACLE_FRONTLEFT,
      IN_OBSTACLE_FRONTRIGHT,
      IN_OBSTACLE_LEFT,
      IN_OBSTACLE_RIGHT,
      IN_NORMAL             
  tasks
    m_robotState.taskNow
      BEGIN_TASK,
      GOBACKLEFT_TASK,
      GOBACKRIGHT_TASK,
      GOTURNRIGHT_TASK,
      GOTURNLEFT_TASK,
      STANDTURNRIGHT_TASK,
      STANDTURNLEFT_TASK,
      STANDTURNRIGHT2_TASK,
      STANDTURNLEFT2_TASK,
      GO_TASK,
      STAND_TASK,
      DOWN_TASK,
      RECOVER_LEFT_TASK,
      RECOVER_RIGHT_TASK,
      FLIP_TASK,
      DEFAULT_TASK
    m_robotState.taskPriorityNow
      PRIORITY_HIGH,
      PRIORITY_NORM,
      PRIORITY_LOW,
    m_robotState.patternNow
      P_DOSTAND,
      P_STANDTOGO,
      P_GOTOSTAND,
      P_STANDGO,
      P_STANDGOLEFT,
      P_STANDGORIGHT,
      P_GOFORWARD,
      P_GOLEFT,
      P_GORIGHT,
      P_GOBACK,
      P_GOBACKLEFT,
      P_GOBACKRIGHT,
      P_DOLOW,
      P_DODOWN,
      P_RECOVERLEFT,
      P_RECOVERRIGHT,
      P_DOFLIP,
      P_DONE,
      P_SETDIRECTION,
      P_RESETDIRECTION,
      P_RESTOREDIRECTION,
      P_RESETGIRO,
      P_BENDSTART,
      P_CRAWLSTART,
      P_SWIMSTART,
      P_INOSTART,
      P_RUNSTART,
      P_ROLLSTART,
      P_NORMALSTART,
      P_REPEAT,
      P_GETCURRENT,
      P_SETPRIORITY_HIGH,
      P_SETPRIORITY_NORM,
      P_SETPRIORITY_LOW,
      P_END

*/
